name: CI/CD Pipeline for mvcluster

on:
  push:
    branches:
      - test         # Pour les tests en push sur 'test' ddev
    tags:
      - 'v*.*.*'     # Pour les releases (ex: v1.0.0)
  pull_request:
    branches:
      - main         # Pour les PR vers la branche principale

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest flake8

      - name: Lint code
        run: |
          flake8 mvcluster tests

      - name: Install mvcluster in editable mode
        run: |
          pip install -e .

      - name: Run tests (if present)
        run: |
          if compgen -G "tests/test_*.py" > /dev/null; then
            pytest tests/
          else
            echo "No tests found."
          fi

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: test
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install build twine

      - name: Add project root to PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV

      - name: Build the package
        run: |
          python -m build

      - name: Publish to PyPI
        run: |
          python -m twine upload dist/*
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
