name: Publish Sphinx docs

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinx-rtd-theme sphinx-autodoc-typehints

      - name: Install project requirements
        run: |
          if [ -f requirements/requirements.txt ]; then
            pip install -r requirements/requirements.txt
          fi

      - name: Lister le dossier courant
        run: |
          pwd
          ls -alR

      - name: Vérifier le dossier docs
        run: |
          echo "Contenu du dossier courant juste avant Sphinx :"
          pwd
          ls -al
          echo "Contenu du dossier docs :"
          ls -al docs || echo "Le dossier docs n'existe pas"
          ls -al docs/source || echo "Le dossier docs/source n'existe pas"

      - name: Build Sphinx documentation
        run: |
          pwd
          sphinx-build -b html docs/source docs/build/html

      - name: Add .nojekyll file
        run: |
          touch docs/build/html/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html
          publish_branch: gh-pages