name: Publish Sphinx docs

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Dump workspace
        run: ls -R .

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinx-rtd-theme sphinx-autodoc-typehints

      - name: Build Sphinx documentation
        # Either adjust the path:
        run: sphinx-build -b html mvcluster/mvcluster/docs/source mvcluster/mvcluster/docs/build/html
        # …or run in the subfolder:
        # working-directory: mvcluster
        # run: sphinx-build -b html docs/source docs/build/html

      - name: Disable Jekyll
        run: touch mvcluster/mvcluster/docs/build/html/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: mvcluster/mvcluster/docs/build/html
