# .github/workflows/docs.yml
name: Publish Sphinx docs

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      # 1. Récupérer le dépôt
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Installer Python 3.11
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3. Installer Sphinx et extensions
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinx-rtd-theme sphinx-autodoc-typehints

      # 4. (Optionnel) Vérifier la structure du dépôt
      - name: Vérifier la structure du dépôt
        run: |
          echo "Répertoire courant : $(pwd)"
          echo "Contenu du dépôt :"
          ls -R .

      # 5. Construire la doc Sphinx
      - name: Build Sphinx documentation
        run: |
          echo "🔨 Construction de la documentation Sphinx"
          echo " → Source : docs/source"
          echo " → Destination : docs/build/html"
          sphinx-build -b html docs/source docs/build/html

      # 6. Désactiver Jekyll
      - name: Add .nojekyll file
        run: |
          touch docs/build/html/.nojekyll

      # 7. Déployer sur GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html
          publish_branch: gh-pages
