# .github/workflows/docs.yml
name: Publish Sphinx docs

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout your repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Setup Python
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 3. Install Sphinx and extensions
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinx-rtd-theme sphinx-autodoc-typehints

      # 4. Build the Sphinx docs from mvcluster/docs/source → mvcluster/docs/build/html
      - name: Build Sphinx documentation
        run: sphinx-build -b html mvcluster/docs/source mvcluster/docs/build/html

      # 5. Disable Jekyll so GitHub Pages serves raw HTML
      - name: Disable Jekyll
        run: touch mvcluster/docs/build/html/.nojekyll

      # 6. Deploy to GitHub Pages (branch gh-pages)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: mvcluster/docs/build/html
