name: Publish Sphinx docs

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Recherche dynamique du dossier source Sphinx
      - name: Locate Sphinx source directory
        run: |
          echo "🔍 Début de la recherche depuis $(pwd)"
          DIR=""
          # Cherche tout dossier contenant conf.py
          for candidate in $(find . -type f -name conf.py); do
            SRC_DIR=$(dirname "$candidate")
            echo "  • Candidat : $SRC_DIR"
            DIR="$SRC_DIR"
            echo "✅ Répertoire source validé : $DIR"
            break
          done

          if [ -z "$DIR" ]; then
            echo "❌ ERREUR : Aucun dossier contenant conf.py trouvé."
            exit 1
          fi

          echo "SOURCE_DIR=$DIR" >> $GITHUB_ENV
          BUILD_PARENT=$(dirname "$DIR")
          BUILD_DIR="$BUILD_PARENT/build/html"
          echo "BUILD_DIR=$BUILD_DIR" >> $GITHUB_ENV

      # 3. Setup Python
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 4. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinx-rtd-theme sphinx-autodoc-typehints

      # 5. Build Sphinx docs
      - name: Build Sphinx documentation
        run: |
          echo "🚀 Construction de la doc Sphinx"
          echo "   • Source : $SOURCE_DIR"
          echo "   • Output : $BUILD_DIR"
          echo "-> Dossier courant : $(pwd)"
          echo "-> Contenu parent de la source :"
          ls -R "$(dirname "$SOURCE_DIR")"
          sphinx-build -b html "$SOURCE_DIR" "$BUILD_DIR" \
            || { echo "❌ sphinx-build a échoué"; exit 1; }

      # 6. Disable Jekyll
      - name: Disable Jekyll
        run: |
          touch "$BUILD_DIR/.nojekyll"

      # 7. Deploy
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: $BUILD_DIR